# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &default_twitter
  twitter_api_key: '9wS454iqVaZOtCq421eqW2Uki'
  twitter_api_secret: 'KMGYzNDO0Q31hR00Wa7bDMEIQLmuMVTk7aMhCUSYqb0w1bTSZK'

development:
  secret_key_base: fd5583b591c14159f3350aca8fc8d33a8d636759e1281efb6e8e62a4a1586a3f5c2ffd287bd01ff310573a8b044069ead61051a3cb061fc511079f9b5003326b
  <<: *default_twitter

test:
  secret_key_base: 569b9c6d9a7cf7829d404b91a96c288e9ff67c66d36f3c3dc987257d9978444651e30a8bcb0c4b536f0c467846eb3c33449feda2bda8dc58bb570db07ba99f5a
  <<: *default_twitter

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_api_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
